version: '3.4'
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: developer-challenge
    volumes:
      - postgres_sdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  postgres_sdata: