spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/developer-challenge
    username: postgres
    password: password
  jpa:
    open-in-view: false
  flyway:
    clean-on-validation-error: true
    locations: classpath:/db/migration

