CREATE TABLE countries
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(20),
    capital    VARCHAR(50),
    region     VARCHAR(255),
    sub_region VARCHAR(50),
    area       INTEGER,
    UNIQUE (name),
    CONSTRAINT pk_country PRIMARY KEY (id)
);